import time
import random


def inspo():
  print("Ok!")
  y = random.choice(["Be yourself; everyone else is already taken.","Be the change that you wish to see in the world.","Live as if you were to die tomorrow. Learn as if you were to live forever.","Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.","There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.","We are all in the gutter, but some of us are looking at the stars.","I have not failed. I've just found 10,000 ways that won't work.","I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.","The purpose of our lives is to be happy.","Get busy living or get busy dying.","Life is what happens when you’re busy making other plans.","Many of life’s failures are people who did not realize how close they were to success when they gave up.","If you want to live a happy life, tie it to a goal, not to people or things.","Never let the fear of striking out keep you from playing the game.","The big lesson in life is never be scared of anyone or anything.","Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth.","Curiosity about life in all of its aspects, I think, is still the secret of great creative people.","Life is not a problem to be solved, but a reality to be experienced.","Turn your wounds into wisdom."])
  x = random.choice(["George","Eve","Ava","John","Josh","Bob","Steve","Mary","Andrew","Charles","Eric","Macey","Jack","Jasckson","Mike","Mia","Eliana","Lucas","Skyler","Zoe","Judy","Olivia","Jasmine","Leo","Alessia","Noah"])
  time.sleep(1)
  print("                --",x,"--")
  time.sleep(1.5)
  print("You: Can you please give me an inporational quote?")
  time.sleep(2)
  print(x,"is typing...")
  time.sleep(1)
  print(x,": Sure!")
  time.sleep(1)
  print(x,"is typing...")
  time.sleep(2)
  print(x,":",y)
  time.sleep(5)
  print("You: Thanks!")

def insult():
  print("Ok!")
  y = random.choice(["You are just like an ape except covered in human flesh","I bet your parents change the subject when their friends ask about you","Are you dum???","I'd say you're 'dumb as a rock,' but at least a rock can hold a door open","If you were the light at the end of the tunnel, I’d turn back around.","I'd give you a nasty look, but you've already got one.","I find the fact that you've lived this long both surprising and disappointing.","You are the reason why shampoo has instructions.","You should carry a plant around with you to replace the oxygen you waste.","Even through the computer I can smell your nasty breath","You look like a before picture of some nasty article.","Why play so hard to get when you're already so hard to want?","Whoever told you to be yourself couldn't have given you worse advice.","You haven't been yourself lately. We've all noticed the improvement."])
  x = random.choice(["George","Eve","Ava","John","Josh","Bob","Steve","Mary","Andrew","Charles","Eric","Macey","Jack","Jasckson","Mike","Mia","Eliana","Lucas","Skyler","Zoe","Judy","Olivia","Jasmine","Leo","Alessia","Noah"])
  time.sleep(1)
  print("                --",x,"--")
  time.sleep(1.5)
  print("You: Can you please give me an insult?")
  time.sleep(2)
  print(x,"is typing...")
  time.sleep(1)
  print(x,": Sure!")
  time.sleep(1)
  print(x,"is typing...")
  time.sleep(2)
  print(x,":",y)
  time.sleep(5)
  print("You: Thanks!")



def feelbetter():
  print("Ok!")
  y = random.choice(["You are alive and so you have worth.", "Saying no isn’t a negative thing.", " It’s okay to take some me-time.", "You are capable of anything.", "Give everthing your best shot, No matter what.", "You are special.","Have confidence in yourself to succeed."])
  x = random.choice(["George","Eve","Ava","John","Josh","Bob","Steve","Mary","Andrew","Charles","Eric","Macey","Jack","Jasckson","Mike","Mia","Eliana","Lucas","Skyler","Zoe","Judy","Olivia","Jasmine","Leo","Alessia","Noah"])
  time.sleep(1)
  print("                --",x,"--")
  time.sleep(1.5)
  print("You: Can you please tell me something to feel better?")
  time.sleep(2)
  print(x,"is typing...")
  time.sleep(1)
  print(x,": Sure!")
  time.sleep(1)
  print(x,"is typing...")
  time.sleep(2)
  print(x,":",y)
  time.sleep(5)
  print("You: Thanks!")

def advice():
  print("Ok!")
  y = random.choice(["Have the courage to live a life true to yourself, not the life others expect of you.","Don’t make decisions when you’re angry. Don’t make promises when you’re happy","Never argue with a stupid person, they’ll drag you down to their level and beat you with experience.","Only pack what you can carry yourself.","Remember you’ll always regret what you didn’t do rather than what you did.","If you blame it on someone else, don’t expect it to get better.","You can be the ripest, juiciest peach in the world, but there will always be someone who hates peaches.","Don’t give up what you want most for what you want now.","Wait 24 hours before getting mad and reacting about anything. If it doesn’t bother you in 24 hours time, it probably isn’t important enough to get mad over."])
  x = random.choice(["George","Eve","Ava","John","Josh","Bob","Steve","Mary","Andrew","Charles","Eric","Macey","Jack","Jasckson","Mike","Mia","Eliana","Lucas","Skyler","Zoe","Judy","Olivia","Jasmine","Leo","Alessia","Noah"])
  time.sleep(1)
  print("                --",x,"--")
  time.sleep(1.5)
  print("You: Can you please give me some advice?")
  time.sleep(2)
  print(x,"is typing...")
  time.sleep(1)
  print(x,": Sure!")
  time.sleep(1)
  print(x,"is typing...")
  time.sleep(2)
  print(x,":",y)
  time.sleep(5)
  print("You: Thanks!")